// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiRVDN5uhxc-u3eynLvz6NE4wv4DBoTjw',
    appId: '1:840922301572:web:28da76561a335b7525eed1',
    messagingSenderId: '840922301572',
    projectId: 'smart-tourist-safety-e802e',
    authDomain: 'smart-tourist-safety-e802e.firebaseapp.com',
    storageBucket: 'smart-tourist-safety-e802e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcw9QPVwv7ww8qFqF4ZdHEYCnuS3LkQHg',
    appId: '1:840922301572:android:1ac2b551c6cc7c2825eed1',
    messagingSenderId: '840922301572',
    projectId: 'smart-tourist-safety-e802e',
    storageBucket: 'smart-tourist-safety-e802e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpEhs4dp1ZEI77hHNrm_-NflUYatxDbOE',
    appId: '1:840922301572:ios:c5d6eabd637a816425eed1',
    messagingSenderId: '840922301572',
    projectId: 'smart-tourist-safety-e802e',
    storageBucket: 'smart-tourist-safety-e802e.firebasestorage.app',
    iosBundleId: 'com.example.smartTouristSafety',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpEhs4dp1ZEI77hHNrm_-NflUYatxDbOE',
    appId: '1:840922301572:ios:c5d6eabd637a816425eed1',
    messagingSenderId: '840922301572',
    projectId: 'smart-tourist-safety-e802e',
    storageBucket: 'smart-tourist-safety-e802e.firebasestorage.app',
    iosBundleId: 'com.example.smartTouristSafety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiRVDN5uhxc-u3eynLvz6NE4wv4DBoTjw',
    appId: '1:840922301572:web:bfda4c673e58160125eed1',
    messagingSenderId: '840922301572',
    projectId: 'smart-tourist-safety-e802e',
    authDomain: 'smart-tourist-safety-e802e.firebaseapp.com',
    storageBucket: 'smart-tourist-safety-e802e.firebasestorage.app',
  );
}
